### ISSUE TITLE
Freezing with latest version of TATW

### ISSUE THREAD

**Issue by ChiefLogan3010** [FrogCraft-Rebirth/FrogCraft-Rebirth#53] opened 2019-04-03 01:08 UTC
I'm not too sure if this mod is still being worked on, but I'm getting a complete freeze of the game whenever placing a frogcraft machine with TATW installed.

**Comment by 3TUSK** [comment] 2019-04-03 01:56
In #43 there was an freezing issue that looks very similar to your description - did you use the latest release of FrogCraft: Rebirth available?

**Comment by ChiefLogan3010** [comment] 2019-04-03 12:13
I'm using frogcraft 2.2.1, IC2 2.8.109 and I've tried with TATW on their latest release (1.01.2) and their latest beta (1.01.2.b27) with both having the same issue.

I've set up an instance with only IC2, Frogcraft, JEI, TATW and it's dependency AromaCore and my latest log looks like this:
https://gist.github.com/ChiefLogan3010/134c39ac0edd96dc05ea84d7b2ff6f9d
The last section of the log loops for another 2.5 million lines but I thought this would be enough.
After placing a block from Frograft it becomes impossible to close the window from within-game and I had to use task manager to kill both the game and the launcher.

This should all have been in my original issue but it was late last night and I wasn't sure the mod was maintained.

**Comment by 3TUSK** [comment] 2019-04-03 16:37
It is still being maintained - but the planned 3.0.0 version changed internal *a lot* and really took me a very long period of time.

I will investigate the freezing issue and make a hot fix if once confirmed.

**Comment by 3TUSK** [comment] 2019-04-03 21:50
Just a heads up, the issue was actually fixed since FrogCraft: Rebirth 2.2.2 but that version was never published on CurseForge. My apology. I will put the 2.2.3 onto CurseForge ASAP; before CurseForge approve the release you can get it from at: https://github.com/3TUSK/FrogCraft-Rebirth/releases (use the `frogcraftrebirth-2.2.3.jar`)

Side note: do not use that 3.0.0 version; it has not been tested and I am certain it will break old saves.

**Comment by 3TUSK** [comment] 2019-04-03 21:52
This is technically a duplicate of #43 but until the fixed version is on CurseForge, this will remain open.

**Comment by ChiefLogan3010** [comment] 2019-04-03 22:52
Thanks! Look forward to integrating this mod into my pack!

**Comment by 3TUSK** [comment] 2019-04-03 23:27
https://minecraft.curseforge.com/projects/frogcraft-rebirth/files/2695262
And the review process was somehow really fast. FrogCraft: Rebirth 2.2.3 is now on CurseForge. Were there any new issue, open another issue ticket instead.

**Closed as completed by 3TUSK** 2019-04-03 23:27 UTC
Labels: Bug, Duplicate, Inter-mod
